version: '3.8'

services:
  
  networks:
    inception:
      name: inception

  volumes:
    DB:
      driver_opts:
        o: bind
        type: none
        device: ${PROJECT_VOLUME_DATABASE}
    WordPress:
      driver_opts:
        o: bind
        type: none
        device: ${PROJECT_VOLUME_WORDPRESS}

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:mwen
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    image: nginx:mwen
    container_name: nginx
    # depends_on: 
      # - wordpress
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    restart: unless-stopped


