version: '3.8'

networks:
  inception:
    name: inception

volumes:
  DB:
    name: DB
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_VOLUME_DATABASE}
  WordPress:
    name: WordPress
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_VOLUME_WORDPRESS}

services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:mwen
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:mwen
    container_name: wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    image: nginx:mwen
    container_name: nginx
    depends_on: 
      - wordpress
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    restart: unless-stopped

################
## Bonus part ##
################

  redis:
    build: ./requirements/bonus/redis
    image: redis:mwen
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    depends_on: 
      - nginx
    volumes:
      - WordPress:/var/run/vsftpd
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:mwen
    container_name: adminer
    depends_on: 
      - redis
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  ftp-serv:
    build: ./requirements/bonus/ftp-server
    image: ftp-serv:mwen
    container_name: ftp-serv
    ports:
      - 21:21
      - 21100-21110:21100-21110
    depends_on: 
      - adminer
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  my_web:
    build: ./requirements/bonus/my_website
    image: my_web:mwen
    container_name: my_web
    depends_on:
      - adminer
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  irc:
    build: ./requirements/bonus/irc
    image: irc:mwen
    container_name: irc
    depends_on:
      - my_web
    restart: unless-stopped


 
