version: '3.8'

services:
  
  networks:
    inception:
      name: inception

  volumes:
  DB:
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_VOLUME_DATABASE}
  WordPress:
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_VOLUME_WORDPRESS}

  nginx:
    build: ./requirements/nginx
    image: nginx:mwen
    container_name: nginx
    restart: always
    # depends_on: 
      # - wordpress
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:mwen
    container_name: wordpress
    restart: always
    ports:
      - 9000:9000
    # depends_on: 
      # - database
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
