
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PWD';

CREATE DATABASE IF NOT EXISTS $MARIADB_DB_NAME;

CREATE USER IF NOT EXISTS '$MARIADB_USER_NAME'@'%' IDENTIFIED BY '$MARIADB_USER_PWD';
GRANT ALL PRIVILEGES ON $MARIADB_DB_NAME.* TO '$MARIADB_USER_NAME'@'%';

FLUSH PRIVILEGES;